### ISSUE TITLE
Handle page request errors in category_downloader.py and wikitimetravel.py

### ISSUE THREAD

**Issue by hpincket** [indirap/state-of-states#1]
Occasionally we run into a 503 error or something like that, which crashes the scraper. It would be nice if we caught this case and tried the url a certain number of times (3?) until it worked. If it still doesn't work we can perhaps write the url out to a different file so that we can check it later?
Not terribly important yet, but this will make it more reliable to run overnight.

**Comment by hpincket** [comment]
This was implemented.

**Comment by hpincket** [comment]
Yeah, I fixed it in only one place before. I think wikitimetravel.py need to do this too. Or is the problem something else?

**Comment by indirap** [comment]
Sorry, accidentally reopened this!
